---
title: "Example Plots"
date: "`r Sys.Date()`"
author: "Meini Tang"
pdf-engine: pdflatex
format: 
  pdf:
    include-in-header:
      text: |
        \usepackage{geometry}
        \usepackage{booktabs}
        \usepackage{float}
        \usepackage{pdflscape}
        \usepackage{hhline}
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 2
    fig-align: 'center'
    fig-pos: 'H'
    keep-tex: true
    tbl-cap-location: bottom
    layout-valign: bottom
error: true
---

```{r}
#| label: source code
save_figures <- TRUE
plot_figures <- TRUE

fig_width_rect <- 11.5
fig_height_rect <- 4

fig_width_square <- 13.8
fig_height_square <- 10.1

kstep_forecast_err <- 10


library(ggplot2)
library(gridExtra)

repo <- "/Users/meinitang/Dropbox/Repository/poisson-dlm"
Rcpp::sourceCpp(file.path(repo, "export.cpp"))

source(file.path(repo, "plot_timeseries_creditble_interval.r"))
source(file.path(repo, "load_data.r"))
source(file.path(repo, "external_methods.r"))

dpath <- "/Users/meinitang/Dropbox/Research/Project1"
opath <- "/Users/meinitang/Dropbox/Research/Project1/simulation"
opath_real <- "/Users/meinitang/Dropbox/Research/Project1/real"
```



## S1. seed = 3269

```{r}
#| label: load data
seed <- 3269

sim1.dat <- load_dat(opath, seed)
sim1.dat <- load_sim(seed, sim1.dat)
print(ls(envir = sim1.dat))

dat <- get_dat_sim_loss_all(sim1.dat)
print(dat)
```

### Data

```{r}
p1 <- ggplot(
    data = data.frame(y = sim1.dat$sim1$y, t = 0:(length(sim1.dat$sim1$y) - 1)),
    aes(x = t, y = y)
) +
    geom_line() +
    theme_light() +
    xlab("Time t") +
    ylab("Observed Count Values y")

p2 <- ggplot(
    data = data.frame(psi = sim1.dat$sim1$psi, t = 0:(length(sim1.dat$sim1$psi) - 1)),
    aes(x = t, y = psi)
) +
    geom_line() +
    theme_light() +
    xlab("Time t") +
    ylab("Latent State psi")


p <- arrangeGrob(grobs = list(y = p1, psi = p2), ncol = 1)

plot(p)

```

### k-step forecasting error

```{r}
dat1 <- subset_dat_loss_all(dat, kstep_forecast_err, "W")
p1 <- plot_mfe(dat1)
p1 <- p1 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))



dat2 <- subset_dat_loss_all(dat, kstep_forecast_err, "Wt")
dat2 <- data.frame(
    k = dat$k[1:10],
    `LBA` = dat$`LBA.DF`[1:10],
    `MCS` = dat$MCS.DF[1:10],
    `FFBS` = dat$FFBS.DF[1:10],
    EpiEstim = dat$EPI[1:10],
    WT = dat$WT[1:10]
)


p2 <- plot_mfe(dat2)
p2 <- p2 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))



dat3 <- subset_dat_loss_all(dat, kstep_forecast_err, "WvsWt")
p3 <- plot_mfe(dat3)
p3 <- p3 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))


if (plot_figures) {
    plot(p1)
    plot(p2)
    plot(p3)
}


if (save_figures) {
    ggsave(
        file.path(
            opath, "forecast",
            paste0("sim-", seed, "-mfe-W.pdf")
        ),
        plot = p1, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )

    ggsave(
        file.path(
            opath, "forecast",
            paste0("sim-", seed, "-mfe-Wt.pdf")
        ),
        plot = p2, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )

    ggsave(
        file.path(
            opath, "forecast",
            paste0("sim-", seed, "-mfe-W-vs-Wt.pdf")
        ),
        plot = p3, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )
}
```

```{r}
dat
```


```{r}
k = 5

p = plot_ts_ci_multi(
  list(
    LBA = sim1.dat$out1.lba$error$forecast$y_cast[1:(length(sim1.dat$sim1$y) - 10),,k],
    # MCS = sim1.dat$out1.mcs$error$forecast$y_cast[1:(length(sim1.dat$sim1$y) - 10),,k],
    # FFBS = sim1.dat$out1.ffbs$error$forecast$y_cast[1:(length(sim1.dat$sim1$y) - 10),,k],
    PL = sim1.dat$out1.pl$error$forecast$y_cast[1:(length(sim1.dat$sim1$y) - 10),,k],
    HVA = sim1.dat$out1.hva$error$forecast$y_cast[1:(length(sim1.dat$sim1$y) - 10),,k],
    MCMC = sim1.dat$out1.mcmc$error$forecast$y_cast[1:(length(sim1.dat$sim1$y) - 10),,k],
    # WT = sim1.dat$out1.wt,
    True = cbind(sim1.dat$sim1$y[1:(length(sim1.dat$sim1$y) - 10)], sim1.dat$sim1$y[1:(length(sim1.dat$sim1$y) - 10)], sim1.dat$sim1$y[1:(length(sim1.dat$sim1$y) - 10)])
  ), 
  legend.position = "top"
)

p = p + ylab(expression(y[t])) + 
  guides(color = guide_legend(nrow = 1)) +
  theme(text = element_text(size = 12))

plot(p)

if (save_figures) {
  ggsave(
        file.path(
            opath, "forecast",
            paste0("sim-", seed, "-", k,"step.pdf")
        ),
        plot = p, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )
}
```


### Posterior of Rt

```{r}
tstart <- 1
ntime <- 200
tend <- tstart + ntime

p <- plot_ts_ci_multi(
    list(
        LBA.DF = log(exp(sim1.dat$out1.lba$fit$psi[tstart:tend, ]) + 1),
        LBA.W = log(exp(sim1.dat$out1.lba2$fit$psi[tstart:tend, ]) + 1),
        # TFS.W = log(exp(sim1.dat$out1.tfs2$fit$psi[tstart:tend, ]) + 1),
        # MCS = log(exp(sim1.dat$out1.mcs$fit$psi[tstart:tend, ]) + 1),
        # FFBS = log(exp(sim1.dat$out1.ffbs2$fit$psi[tstart:tend, ]) + 1),
        PL = log(exp(sim1.dat$out1.tfs3$fit$psi[tstart:tend, ]) + 1),
        HVA = log(exp(sim1.dat$out1.hva$fit$psi[tstart:tend, ]) + 1),
        MCMC = log(exp(sim1.dat$out1.mcmc$fit$psi[tstart:tend, ]) + 1),
        # WT = sim1.dat$out1.wt[tstart:tend, ],
        # EpiEstim = sim1.dat$out1.epi[tstart:tend, ],
        True = log(exp(cbind(sim1.dat$sim1$psi[tstart:tend, ], sim1.dat$sim1$psi[tstart:tend, ], sim1.dat$sim1$psi[tstart:tend, ])) + 1)
    ),
    legend.position = "top", alpha = 0.25
)

p <- p + ylab(expression(R[t])) +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))

plot(p)

if (save_figures) {
    ggsave(
        file.path(
            opath, "posterior",
            paste0("sim-", seed, "-Rt.pdf")
        ),
        plot = p, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )
}
```


### Posterior of Static Parameters

#### W

```{r}
if ("W" %in% names(sim1.dat$out1.pl$fit)) {
    tag <- paste0("sim-", seed, "-pl-")
    p <- plot_param(
        c(sim1.dat$out1.pl$fit$W),
        data_true = NULL,
        tag = "W", title = FALSE, plot_figures = plot_figures
    )

    if (save_figures) {
        ggsave(
            file.path(
                opath, "posterior",
                paste0(tag, "posterior-W.pdf")
            ),
            plot = p, device = "pdf", dpi = 300,
            height = fig_height_square, width = fig_width_square
        )
    }
}
```

```{r}
if ("W" %in% names(sim1.dat$out1.hva$fit)) {
    tag <- paste0("sim-", seed, "-hva-")
    p <- plot_param(
        c(sim1.dat$out1.hva$fit$W), 
        data_true = NULL, 
        tag = "W", title = FALSE, plot_figures = plot_figures)

    if (save_figures) {
        ggsave(
            file.path(
                opath, "posterior",
                paste0(tag, "posterior-W.pdf")
            ),
            plot = p, device = "pdf", dpi = 300,
            height = fig_height_square, width = fig_width_square
        )
    }
}
```

```{r}
if ("W" %in% names(sim1.dat$out1.mcmc$fit)) {
    tag <- paste0("sim-", seed, "-mcmc-")
    p <- plot_param(
        c(sim1.dat$out1.mcmc$fit$W), 
        data_true = NULL, 
        tag = "W", title = FALSE, plot_figures = plot_figures)

    if (save_figures) {
        ggsave(
            file.path(
                opath, "posterior",
                paste0(tag, "posterior-W.pdf")
            ),
            plot = p, device = "pdf", dpi = 300,
            height = fig_height_square, width = fig_width_square
        )
    }
}
```

```{r}
rm(sim1.dat)
```

## S2. seed = 2793

```{r}
#| label: load data 2793
seed <- 2793

sim2.dat <- load_dat(opath, seed)
sim2.dat <- load_sim(seed, sim2.dat)
print(ls(envir = sim2.dat))

dat <- get_dat_sim_loss_all(sim2.dat)
print(dat)
```

### Data

```{r}

p1 <- ggplot(
    data = data.frame(y = sim2.dat$sim1$y, t = 0:(length(sim2.dat$sim1$y) - 1)),
    aes(x = t, y = y)
) +
    geom_line() +
    theme_light() +
    xlab("Time t") +
    ylab("Observed Count Values y")

p2 <- ggplot(
    data = data.frame(psi = sim2.dat$sim1$psi, t = 0:(length(sim2.dat$sim1$psi) - 1)),
    aes(x = t, y = psi)
) +
    geom_line() +
    theme_light() +
    xlab("Time t") +
    ylab("Latent State psi")


p <- arrangeGrob(grobs = list(y = p1, psi = p2), ncol = 1)

plot(p)
```

### k-step forecasting error

```{r}
dat1 <- subset_dat_loss_all(dat, kstep_forecast_err, "W")
p1 <- plot_mfe(dat1)
p1 <- p1 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))



dat2 <- subset_dat_loss_all(dat, kstep_forecast_err, "Wt")
dat2 <- data.frame(
    k = dat$k[1:10],
    `LBA` = dat$`LBA.DF`[1:10],
    `MCS` = dat$MCS.DF[1:10],
    `FFBS` = dat$FFBS.DF[1:10],
    EpiEstim = dat$EPI[1:10],
    WT = dat$WT[1:10]
)


p2 <- plot_mfe(dat2)
p2 <- p2 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))



dat3 <- subset_dat_loss_all(dat, kstep_forecast_err, "WvsWt")
p3 <- plot_mfe(dat3)
p3 <- p3 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))


if (plot_figures) {
    plot(p1)
    plot(p2)
    plot(p3)
}


if (save_figures) {
    ggsave(
        file.path(
            opath, "forecast",
            paste0("sim-", seed, "-mfe-W.pdf")
        ),
        plot = p1, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )

    ggsave(
        file.path(
            opath, "forecast",
            paste0("sim-", seed, "-mfe-Wt.pdf")
        ),
        plot = p2, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )

    ggsave(
        file.path(
            opath, "forecast",
            paste0("sim-", seed, "-mfe-W-vs-Wt.pdf")
        ),
        plot = p3, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )
}
```

```{r}
dat
```

```{r}
for (k in c(1, 5, 10)) {
    p <- plot_ts_ci_multi(
        list(
            LBA = sim2.dat$out1.lba$error$forecast$y_cast[1:(length(sim2.dat$sim1$y) - 10), , k],
            MCS = sim2.dat$out1.mcs$error$forecast$y_cast[1:(length(sim2.dat$sim1$y) - 10), , k],
            FFBS = sim2.dat$out1.ffbs$error$forecast$y_cast[1:(length(sim2.dat$sim1$y) - 10), , k],
            PL = sim2.dat$out1.pl$error$forecast$y_cast[1:(length(sim2.dat$sim1$y) - 10), , k],
            # HVA = sim2.dat$out1.hva$error$forecast$y_cast[1:(length(sim2.dat$sim1$y) - 10),,k],
            # MCMC = sim2.dat$out1.mcmc$error$forecast$y_cast[1:(length(sim2.dat$sim1$y) - 10),,k],
            True = cbind(sim2.dat$sim1$y[1:(length(sim2.dat$sim1$y) - 10)], sim2.dat$sim1$y[1:(length(sim2.dat$sim1$y) - 10)], sim2.dat$sim1$y[1:(length(sim2.dat$sim1$y) - 10)])
        ),
        legend.position = "top"
    )

    p <- p + ylab(expression(R[t])) +
        guides(color = guide_legend(nrow = 1)) +
        theme(text = element_text(size = 12)) +
        ylab(expression(y[t]))

    if (plot_figures) {
        plot(p)
    }

    if (save_figures) {
        ggsave(
            file.path(
                opath, "forecast",
                paste0("sim-", seed, "-", k, "step.pdf")
            ),
            plot = p, device = "pdf", dpi = 300,
            width = fig_width_rect, height = fig_height_rect
        )
    }
}


```



### Posterior of Rt

```{r}
tstart <- 30
ntime <- 140
tend <- tstart + ntime

p <- plot_ts_ci_multi(
    list(
        LBA = log(exp(sim2.dat$out1.lba$fit$psi[tstart:tend, ]) + 1),
        MCS = log(exp(sim2.dat$out1.mcs$fit$psi[tstart:tend, ]) + 1),
        FFBS = log(exp(sim2.dat$out1.ffbs$fit$psi[tstart:tend, ]) + 1),
        PL = log(exp(sim2.dat$out1.pl$fit$psi[tstart:tend, ]) + 1),
        HVA = log(exp(sim2.dat$out1.hva$fit$psi[tstart:tend, ]) + 1),
        MCMC = log(exp(sim2.dat$out1.mcmc$fit$psi[tstart:tend, ]) + 1),
        WT = sim2.dat$out1.wt[tstart:tend, ],
        EpiEstim = sim2.dat$out1.epi[tstart:tend, ],
        True = log(exp(cbind(sim2.dat$sim1$psi[tstart:tend, ], sim2.dat$sim1$psi[tstart:tend, ], sim2.dat$sim1$psi[tstart:tend,])) + 1)
    ),
    legend.position = "top"
)

p <- p + ylab(expression(R[t])) +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))

plot(p)

if (save_figures) {
    ggsave(
        file.path(
            opath, "posterior",
            paste0("sim-", seed, "-Rt.pdf")
        ),
        plot = p, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )
}
```

```{r}
rm(sim2.dat)
```


## S3. seed = 8434

```{r}
#| label: load data 8434
seed <- 8434

sim3.dat <- load_dat(opath, seed)
sim3.dat <- load_sim(seed, sim3.dat)
print(ls(envir = sim3.dat))

dat <- get_dat_sim_loss_all(sim3.dat)
print(dat)
```


### Data

```{r}
p1 <- ggplot(
    data = data.frame(y = sim3.dat$sim1$y, t = 0:(length(sim3.dat$sim1$y) - 1)),
    aes(x = t, y = y)
) +
    geom_line() +
    theme_light() +
    xlab("Time t") +
    ylab("Observed Count Values y")

p2 <- ggplot(
    data = data.frame(psi = sim3.dat$sim1$psi, t = 0:(length(sim3.dat$sim1$psi) - 1)),
    aes(x = t, y = psi)
) +
    geom_line() +
    theme_light() +
    xlab("Time t") +
    ylab("Latent State psi")


p <- arrangeGrob(grobs = list(y = p1, psi = p2), ncol = 1)

plot(p)
```

### k-step forecasting error

```{r}
dat1 <- subset_dat_loss_all(dat, kstep_forecast_err, "W")
p1 <- plot_mfe(dat1)
p1 <- p1 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))



dat2 <- subset_dat_loss_all(dat, kstep_forecast_err, "Wt")
dat2 <- data.frame(
    k = dat$k[1:10],
    `LBA` = dat$`LBA.DF`[1:10],
    `MCS` = dat$MCS.DF[1:10],
    `FFBS` = dat$FFBS.DF[1:10],
    EpiEstim = dat$EPI[1:10],
    WT = dat$WT[1:10]
)


p2 <- plot_mfe(dat2)
p2 <- p2 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))



dat3 <- subset_dat_loss_all(dat, kstep_forecast_err, "WvsWt")
p3 <- plot_mfe(dat3)
p3 <- p3 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))


if (plot_figures) {
    plot(p1)
    plot(p2)
    plot(p3)
}


if (save_figures) {
    ggsave(
        file.path(
            opath, "forecast",
            paste0("sim-", seed, "-mfe-W.pdf")
        ),
        plot = p1, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )

    ggsave(
        file.path(
            opath, "forecast",
            paste0("sim-", seed, "-mfe-Wt.pdf")
        ),
        plot = p2, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )

    ggsave(
        file.path(
            opath, "forecast",
            paste0("sim-", seed, "-mfe-W-vs-Wt.pdf")
        ),
        plot = p3, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )
}
```

```{r}
dat
```

```{r}
k <- 1
for (k in c(1, 5, 10)) {
    p <- plot_ts_ci_multi(
        list(
            LBA = sim3.dat$out1.lba$error$forecast$y_cast[1:(length(sim3.dat$sim1$y) - 10), , k],
            MCS = sim3.dat$out1.mcs$error$forecast$y_cast[1:(length(sim3.dat$sim1$y) - 10), , k],
            FFBS = sim3.dat$out1.ffbs$error$forecast$y_cast[1:(length(sim3.dat$sim1$y) - 10), , k],
            PL = sim3.dat$out1.pl$error$forecast$y_cast[1:(length(sim3.dat$sim1$y) - 10), , k],
            # HVA = sim3.dat$out1.hva$error$forecast$y_cast[1:(length(sim3.dat$sim1$y) - 10), , k],
            # MCMC = sim3.dat$out1.mcmc$error$forecast$y_cast[1:(length(sim3.dat$sim1$y) - 10), , k],
            # WT = sim3.dat$out1.wt,
            True = cbind(sim3.dat$sim1$y[1:(length(sim3.dat$sim1$y) - 10)], sim3.dat$sim1$y[1:(length(sim3.dat$sim1$y) - 10)], sim3.dat$sim1$y[1:(length(sim3.dat$sim1$y) - 10)])
        ),
        legend.position = "top"
    )

    p <- p + ylab(expression(y[t])) +
        guides(color = guide_legend(nrow = 1)) +
        theme(text = element_text(size = 12))

    plot(p)

    if (save_figures) {
        ggsave(
            file.path(
                opath, "forecast",
                paste0("sim-", seed, "-", k, "step.pdf")
            ),
            plot = p, device = "pdf", dpi = 300,
            width = fig_width_rect, height = fig_height_rect
        )
    }
}

```


### Posterior of Rt

```{r}
tstart <- 50
ntime <- 140
tend <- tstart + ntime

p <- plot_ts_ci_multi(
    list(
        LBA = log(exp(sim3.dat$out1.lba$fit$psi) + 1),
        MCS = log(exp(sim3.dat$out1.mcs$fit$psi) + 1),
        FFBS = log(exp(sim3.dat$out1.ffbs$fit$psi) + 1),
        PL = log(exp(sim3.dat$out1.pl$fit$psi) + 1),
        HVA = log(exp(sim3.dat$out1.hva$fit$psi) + 1),
        MCMC = log(exp(sim3.dat$out1.mcmc$fit$psi) + 1),
        EpiEstim = sim3.dat$out1.epi,
        WT = sim3.dat$out1.wt,
        True = log(exp(cbind(sim3.dat$sim1$psi, sim3.dat$sim1$psi, sim3.dat$sim1$psi)) + 1)
    ),
    legend.position = "top"
)

p <- p + ylab(expression(R[t])) +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))

plot(p)

if (save_figures) {
    ggsave(
        file.path(
            opath, "posterior",
            paste0("sim-", seed, "-Rt.pdf")
        ),
        plot = p, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )
}
```


```{r}
rm(sim3.dat)
```


## Santa Cruz

```{r}
tag = "santacruz"
santacruz.dat = load_dat(opath_real,tag, "covid")
santacruz.dat = load_real(dpath, "Santa Cruz", santacruz.dat)
print(ls(santacruz.dat))
```

### k-step forecasting

```{r}
dat <- get_dat_real_loss_all(santacruz.dat)


dat1 <- subset_dat_loss_all(dat, kstep_forecast_err, "W")
p1 <- plot_mfe(dat1)
p1 <- p1 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))



dat2 <- subset_dat_loss_all(dat, kstep_forecast_err, "Wt")
dat2 <- data.frame(
    k = dat$k[1:10],
    `LBA` = dat$`LBA.DF`[1:10],
    `MCS` = dat$MCS.DF[1:10],
    `FFBS` = dat$FFBS.DF[1:10],
    EpiEstim = dat$EPI[1:10],
    WT = dat$WT[1:10]
)


p2 <- plot_mfe(dat2)
p2 <- p2 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))



dat3 <- subset_dat_loss_all(dat, kstep_forecast_err, "WvsWt")
p3 <- plot_mfe(dat3)
p3 <- p3 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))


if (plot_figures) {
    plot(p1)
    plot(p2)
    plot(p3)
}


if (save_figures) {
    ggsave(
        file.path(
            opath_real, "forecast",
            paste0("covid-", tag, "-mfe-W.pdf")
        ),
        plot = p1, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )

    ggsave(
        file.path(
            opath_real, "forecast",
            paste0("covid-", tag, "-mfe-Wt.pdf")
        ),
        plot = p2, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )

    ggsave(
        file.path(
            opath_real, "forecast",
            paste0("covid-", tag, "-mfe-W-vs-Wt.pdf")
        ),
        plot = p3, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )
}
```

```{r}
for (k in c(1, 5, 10)) {
    p <- plot_ts_ci_multi(
        list(
            LBA = santacruz.dat$out.lba$error$forecast$y_cast[1:(length(santacruz.dat$y2) - 10), , k],
            MCS = santacruz.dat$out.mcs$error$forecast$y_cast[1:(length(santacruz.dat$y2) - 10), , k],
            FFBS = santacruz.dat$out.ffbs$error$forecast$y_cast[1:(length(santacruz.dat$y2) - 10), , k],
            PL = santacruz.dat$out.pl$error$forecast$y_cast[1:(length(santacruz.dat$y2) - 10), , k],
            # HVA = santacruz.dat$out.hva$error$forecast$y_cast[1:(length(santacruz.dat$y2) - 10),,k],
            # MCMC = log(exp(santacruz.dat$out1.mcmc$fit$psi) + 1),
            # WT = t(santacruz.dat$forecast.wt$y_cast[,1:(length(santacruz.dat$y2) - 10),k]),
            True = cbind(santacruz.dat$y2[1:(length(santacruz.dat$y2) - 10)], santacruz.dat$y2[1:(length(santacruz.dat$y2) - 10)], santacruz.dat$y2[1:(length(santacruz.dat$y2) - 10)])
        ),
        legend.position = "top"
    )

    p <- p + ylab(expression(y[t])) +
        guides(color = guide_legend(nrow = 1)) +
        theme(text = element_text(size = 12))

    plot(p)

    if (save_figures) {
        ggsave(
            file.path(
                opath_real, "forecast",
                paste0("covid-", tag, "-", k, "step.pdf")
            ),
            plot = p, device = "pdf", dpi = 300,
            width = fig_width_rect, height = fig_height_rect
        )
    }
}


```


### Posterior of Rt

```{r}
tstart <- 50
ntime <- 450
tend <- tstart + ntime

p <- plot_ts_ci_multi(
    list(
        LBA = log(exp(santacruz.dat$out.lba$fit$psi[tstart:tend, ]) + 1),
        MCS = log(exp(santacruz.dat$out.mcs$fit$psi[tstart:tend, ]) + 1),
        FFBS = log(exp(santacruz.dat$out.ffbs$fit$psi[tstart:tend, ]) + 1),
        PL = log(exp(santacruz.dat$out.pl$fit$psi[tstart:tend, ]) + 1),
        # HVA = log(exp(santacruz.dat$out.hva$fit$psi) + 1),
        # MCMC = log(exp(santacruz.dat$out.mcmc$fit$psi) + 1),
        WT = santacruz.dat$out.wt[tstart:tend, ],
        EpiEstim = santacruz.dat$out.epi[tstart:tend, ]
    ),
    legend.position = "top"
)

p <- p + ylab(expression(R[t]))
p <- p + ylab(expression(R[t])) +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))

plot(p)

if (save_figures) {
    ggsave(
        file.path(
            opath_real, "posterior",
            paste0("covid-", tag, "-Rt.pdf")
        ),
        plot = p, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )
}
```


```{r}
rm(santacruz.dat)
```


## Santa Clara

```{r}
tag = "santaclara"
santaclara.dat = load_dat(opath_real, tag, "covid")
santaclara.dat = load_real(dpath, "Santa Clara", santaclara.dat)
print(ls(santaclara.dat))
```

### k-step forecasting error

```{r}
dat <- get_dat_real_loss_all(santaclara.dat)


dat1 <- subset_dat_loss_all(dat, kstep_forecast_err, "W")
p1 <- plot_mfe(dat1)
p1 <- p1 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))



dat2 <- subset_dat_loss_all(dat, kstep_forecast_err, "Wt")
dat2 <- data.frame(
    k = dat$k[1:10],
    `LBA` = dat$`LBA.DF`[1:10],
    `MCS` = dat$MCS.DF[1:10],
    `FFBS` = dat$FFBS.DF[1:10],
    EpiEstim = dat$EPI[1:10],
    WT = dat$WT[1:10]
)


p2 <- plot_mfe(dat2)
p2 <- p2 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))



dat3 <- subset_dat_loss_all(dat, kstep_forecast_err, "WvsWt")
p3 <- plot_mfe(dat3)
p3 <- p3 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))


if (plot_figures) {
    plot(p1)
    plot(p2)
    plot(p3)
}


if (save_figures) {
    ggsave(
        file.path(
            opath_real, "forecast",
            paste0("covid-", tag, "-mfe-W.pdf")
        ),
        plot = p1, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )

    ggsave(
        file.path(
            opath_real, "forecast",
            paste0("covid-", tag, "-mfe-Wt.pdf")
        ),
        plot = p2, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )

    ggsave(
        file.path(
            opath_real, "forecast",
            paste0("covid-", tag, "-mfe-W-vs-Wt.pdf")
        ),
        plot = p3, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )
}
```

```{r}
tstart <- 50
for (k in c(1, 5, 10)) {
    p <- plot_ts_ci_multi(
        list(
            LBA = santaclara.dat$out.lba2$error$forecast$y_cast[tstart:(length(santaclara.dat$y2) - 10), , k],
            MCS = santaclara.dat$out.mcs2$error$forecast$y_cast[tstart:(length(santaclara.dat$y2) - 10), , k],
            FFBS = santaclara.dat$out.ffbs2$error$forecast$y_cast[tstart:(length(santaclara.dat$y2) - 10), , k],
            PL = santaclara.dat$out.pl$error$forecast$y_cast[tstart:(length(santaclara.dat$y2) - 10), , k],
            # HVA = santaclara.dat$out.hva$error$forecast$y_cast[1:(length(santaclara.dat$y2) - 10),,k],
            # MCMC = log(exp(santaclara.dat$out1.mcmc$fit$psi) + 1),
            # WT = santaclara.dat$out1.wt,
            True = cbind(santaclara.dat$y2[tstart:(length(santaclara.dat$y2) - 10)], santaclara.dat$y2[tstart:(length(santaclara.dat$y2) - 10)], santaclara.dat$y2[tstart:(length(santaclara.dat$y2) - 10)])
        ),
        legend.position = "top"
    )

    p <- p + ylab(expression(y[t])) +
        guides(color = guide_legend(nrow = 1)) +
        theme(text = element_text(size = 12))

    plot(p)

    if (save_figures) {
        ggsave(
            file.path(
                opath_real, "forecast",
                paste0("covid-", tag, "-", k, "step.pdf")
            ),
            plot = p, device = "pdf", dpi = 300,
            width = fig_width_rect, height = fig_height_rect
        )
    }
}


```



### Posterior of Rt

```{r}
tstart <- 50
ntime <- 450
tend <- tstart + ntime

p <- plot_ts_ci_multi(
    list(
        LBA = log(exp(santaclara.dat$out.lba$fit$psi[tstart:tend, ]) + 1),
        MCS = log(exp(santaclara.dat$out.mcs$fit$psi[tstart:tend,]) + 1),
        FFBS = log(exp(santaclara.dat$out.ffbs$fit$psi[tstart:tend,]) + 1),
        PL = log(exp(santaclara.dat$out.pl$fit$psi[tstart:tend,]) + 1),
        # HVA = log(exp(santaclara.dat$out.hva$fit$psi[tstart:tend,]) + 1)
        # MCMC = log(exp(santaclara.dat$out.mcmc$fit$psi[tstart:tend,]) + 1),
        WT = santaclara.dat$out.wt[tstart:tend,],
        EpiEstim = santaclara.dat$out.epi[tstart:tend,]
    ),
    legend.position = "top"
)

p <- p + ylab(expression(R[t]))
p <- p + ylab(expression(R[t])) +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))

plot(p)

if (save_figures) {
    ggsave(
        file.path(
            opath_real, "posterior",
            paste0("covid-", tag, "-Rt.pdf")
        ),
        plot = p, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )
}
```


```{r}
rm(santaclara.dat)
gc()
```


## Monterey

```{r}
tag = "monterey"
monterey.dat = load_dat(opath_real, tag, "covid")
monterey.dat = load_real(dpath, "Monterey", monterey.dat)
print(ls(monterey.dat))
```

### k-step forecasting error

```{r}
dat <- get_dat_real_loss_all(monterey.dat)


dat1 <- subset_dat_loss_all(dat, kstep_forecast_err, "W")
p1 <- plot_mfe(dat1)
p1 <- p1 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))



dat2 <- subset_dat_loss_all(dat, kstep_forecast_err, "Wt")
dat2 <- data.frame(
    k = dat$k[1:10],
    `LBA` = dat$`LBA.DF`[1:10],
    `MCS` = dat$MCS.DF[1:10],
    `FFBS` = dat$FFBS.DF[1:10],
    EpiEstim = dat$EPI[1:10],
    WT = dat$WT[1:10]
)


p2 <- plot_mfe(dat2)
p2 <- p2 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))



dat3 <- subset_dat_loss_all(dat, kstep_forecast_err, "WvsWt")
p3 <- plot_mfe(dat3)
p3 <- p3 + ylab("RMSE") +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))


if (plot_figures) {
    plot(p1)
    plot(p2)
    plot(p3)
}


if (save_figures) {
    ggsave(
        file.path(
            opath_real, "forecast",
            paste0("covid-", tag, "-mfe-W.pdf")
        ),
        plot = p1, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )

    ggsave(
        file.path(
            opath_real, "forecast",
            paste0("covid-", tag, "-mfe-Wt.pdf")
        ),
        plot = p2, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )

    ggsave(
        file.path(
            opath_real, "forecast",
            paste0("covid-", tag, "-mfe-W-vs-Wt.pdf")
        ),
        plot = p3, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )
}
```

```{r}
tstart <- 50
for (k in c(1, 5, 10)) {
    p <- plot_ts_ci_multi(
        list(
            LBA = monterey.dat$out.lba2$error$forecast$y_cast[tstart:(length(monterey.dat$y2) - 10), , k],
            MCS = monterey.dat$out.mcs2$error$forecast$y_cast[tstart:(length(monterey.dat$y2) - 10), , k],
            FFBS = monterey.dat$out.ffbs2$error$forecast$y_cast[tstart:(length(monterey.dat$y2) - 10), , k],
            PL = monterey.dat$out.pl$error$forecast$y_cast[tstart:(length(monterey.dat$y2) - 10), , k],
            # HVA = monterey.dat$out.hva$error$forecast$y_cast[tstart:(length(monterey.dat$y2) - 10),,k],
            # MCMC = log(exp(monterey.dat$out1.mcmc$fit$psi) + 1),
            # WT = monterey.dat$out1.wt,
            True = cbind(monterey.dat$y2[tstart:(length(monterey.dat$y2) - 10)], monterey.dat$y2[tstart:(length(monterey.dat$y2) - 10)], monterey.dat$y2[tstart:(length(monterey.dat$y2) - 10)])
        ),
        legend.position = "top"
    )

    p <- p + ylab(expression(y[t])) +
        guides(color = guide_legend(nrow = 1)) +
        theme(text = element_text(size = 12))

    plot(p)

    if (save_figures) {
        ggsave(
            file.path(
                opath_real, "forecast",
                paste0("covid-", tag, "-", k, "step.pdf")
            ),
            plot = p, device = "pdf", dpi = 300,
            width = fig_width_rect, height = fig_height_rect
        )
    }
}

```



### Posterior of Rt

```{r}
tstart <- 50
ntime <- 140
tend <- tstart + ntime

p <- plot_ts_ci_multi(
    list(
        LBA = log(exp(monterey.dat$out.lba2$fit$psi[tstart:tend, ]) + 1),
        MCS = log(exp(monterey.dat$out.mcs2$fit$psi[tstart:tend, ]) + 1),
        FFBS = log(exp(monterey.dat$out.ffbs2$fit$psi[tstart:tend, ]) + 1),
        PL = log(exp(monterey.dat$out.pl$fit$psi[tstart:tend, ]) + 1),
        # HVA = log(exp(monterey.dat$out.hva$fit$psi[tstart:tend,]) + 1),
        MCMC = log(exp(monterey.dat$out.mcmc$fit$psi[tstart:tend,]) + 1),
        WT = monterey.dat$out.wt[tstart:tend, ],
        EpiEstim = monterey.dat$out.epi[tstart:tend, ]
    ),
    legend.position = "top"
)

p <- p + ylab(expression(R[t]))
p <- p + ylab(expression(R[t])) +
    guides(color = guide_legend(nrow = 1)) +
    theme(text = element_text(size = 12))

plot(p)

if (save_figures) {
    ggsave(
        file.path(
            opath_real, "posterior",
            paste0("covid-", tag, "-Rt.pdf")
        ),
        plot = p, device = "pdf", dpi = 300,
        width = fig_width_rect, height = fig_height_rect
    )
}
```



```{r}
rm(monterey.dat)
gc()
```
